Config                            = {}
Config.EnablePlayerManagement     = true
Config.EnableArmoryManagement     = true
Config.EnableESXIdentity          = true -- only turn this on if you are using esx_identity
Config.EnableNonFreemodePeds      = false -- turn this on if you want custom peds
Config.EnableSocietyOwnedVehicles = false
Config.EnableLicenses             = false
Config.Locale                     = 'hr'
Config.Blipovi					  = true
Config.Price 					  = 1500
Config.RepairMultiplier 		  = 1
Config.Tijelo 					  = "sarajlije"
Config.Automafija 				  = "automafija"
Config.Impound 					  = vector3(-2611.5349121094, 1685.0986328125, 140.86622619629)
